grafana:

  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true
    ingressClassName: nginx
    # Annotations for Grafana Ingress
    ##
    annotations: 
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      external-dns.alpha.kubernetes.io/hostname: grafana.tools.goodbyecubicle.com
      #kubernetes.io/ingress.class: alb
    ## Labels to be added to the Ingress
    ##
    labels: {}

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    hosts:
    - grafana.tools.goodbyecubicle.com
    
       ## Path for grafana ingress
    path: /

    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
    ##
    tls:
    - hosts:
      - grafana.tools.goodbyecubicle.com 
      secretName: nginx-tls
  