apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: external-dns-values
    files:
      - values.yaml=values.yaml
      # - values2.yaml=values2.yaml
configurations:
  - kustomizeconfig.yaml
