apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dn
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: external-dns
      version: ~5.4.5
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    aws:
      region: "us-east-2"
      zoneType: "public" # public || private
      evaluateTargetHealth: "true"

    domainFilters:
    - "goodbyecubicle.com" #"production.gettelevet.com"
    #- txtOwnerId: "external-dns-goodbyecubicle-managed" 

    serviceAccount:
      name: external-dns
      namespace: kube-system
      annotations:
        # Substitute your account ID and IAM service role name below.
        eks.amazonaws.com/role-arn: "arn:aws:iam::602955111154:role/dev-gitlab-external-dns" 

      #https://oidc.eks.us-east-2.amazonaws.com/id/428063A53041CAED1AE7F0826BCCB93B
