apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 20.0.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1m
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  install:
    remediation:
      retries: 5
      remediateLastFailure: true
 #OR GET VALUES FROM CONFIGMAP
valuesFrom:
- kind: ConfigMap
  name: monitoring-values
- kind: Secret
  name: monitoring-secrets
 
