apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: kps-values
    behavior: merge
    files:
      - values.yaml=values.yaml
      - values.yaml=secrets.yaml 
configurations:
  - kustomizeconfig.yaml