apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    # Email address used for ACME registration
    email: michael@moonswitch.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
# ---
# apiVersion: cert-manager.io/v1alpha2
# kind: Issuer
# metadata:
#   name: ca-issuer
#   namespace: mongodb
# spec:
#   ca:
#     secretName: ca-key-pair
# ---
# apiVersion: cert-manager.io/v1alpha2
# kind: Certificate
# metadata:
#   name: cert-manager-certificate
#   namespace: mongodb
# spec:
#   secretName: mongodb-tls
#   issuerRef:
#     name: letsencrypt-prod
#     kind: Issuer
#   commonName: "*.mongodb-replica-set-svc.mongodb.svc.cluster.local"
#   organization:
#   - MongoDB