apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx

spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "4.0.6"
  interval: 1h0m0s
  install:
    timeout: 15m
    remediation:
      retries: 5
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    controller:
      service:
        externalTrafficPolicy: Local
      config: 
        http-snippet: |
          server {
            listen 18080;

            location /nginx_status {
              allow all;
              stub_status on;
            }

            location / {
              return 404;
            }
          }

        #30x default of 320
    publishService:
      enabled: true
    admissionWebhooks:
      enabled: true
    
  # This section refers to the creation of the IngressClass resource
  # IngressClass resources are supported since k8s >= 1.18 and required since k8s >= 1.19
    ingressClassResource:
      name: nginx
      enabled: true
      controllerValue: "k8s.io/ingress-nginx"

